package com.restaurant.entity;

public class CommentKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.Id
     *
     * @mbg.generated Tue Mar 12 15:33:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.UserId
     *
     * @mbg.generated Tue Mar 12 15:33:47 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.toPostId
     *
     * @mbg.generated Tue Mar 12 15:33:47 CST 2019
     */
    private Integer topostid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.toCommentId
     *
     * @mbg.generated Tue Mar 12 15:33:47 CST 2019
     */
    private Integer tocommentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.Id
     *
     * @return the value of comment.Id
     *
     * @mbg.generated Tue Mar 12 15:33:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.Id
     *
     * @param id the value for comment.Id
     *
     * @mbg.generated Tue Mar 12 15:33:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.UserId
     *
     * @return the value of comment.UserId
     *
     * @mbg.generated Tue Mar 12 15:33:47 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.UserId
     *
     * @param userid the value for comment.UserId
     *
     * @mbg.generated Tue Mar 12 15:33:47 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.toPostId
     *
     * @return the value of comment.toPostId
     *
     * @mbg.generated Tue Mar 12 15:33:47 CST 2019
     */
    public Integer getTopostid() {
        return topostid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.toPostId
     *
     * @param topostid the value for comment.toPostId
     *
     * @mbg.generated Tue Mar 12 15:33:47 CST 2019
     */
    public void setTopostid(Integer topostid) {
        this.topostid = topostid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.toCommentId
     *
     * @return the value of comment.toCommentId
     *
     * @mbg.generated Tue Mar 12 15:33:47 CST 2019
     */
    public Integer getTocommentid() {
        return tocommentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.toCommentId
     *
     * @param tocommentid the value for comment.toCommentId
     *
     * @mbg.generated Tue Mar 12 15:33:47 CST 2019
     */
    public void setTocommentid(Integer tocommentid) {
        this.tocommentid = tocommentid;
    }
}