package com.restaurant.entity;

import java.util.List;

public class Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.Id
     *
     * @mbg.generated Thu Mar 07 19:47:20 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.companyName
     *
     * @mbg.generated Thu Mar 07 19:47:20 CST 2019
     */
    private String companyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.logo
     *
     * @mbg.generated Thu Mar 07 19:47:20 CST 2019
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.position
     *
     * @mbg.generated Thu Mar 07 19:47:20 CST 2019
     */
    private String position;



    private List<Restaurant> restaurants;

    public List<Restaurant> getRestaurants() {
        return restaurants;
    }

    public void setRestaurants(List<Restaurant> restaurants) {
        this.restaurants = restaurants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.Id
     *
     * @return the value of company.Id
     *
     * @mbg.generated Thu Mar 07 19:47:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.Id
     *
     * @param id the value for company.Id
     *
     * @mbg.generated Thu Mar 07 19:47:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.companyName
     *
     * @return the value of company.companyName
     *
     * @mbg.generated Thu Mar 07 19:47:20 CST 2019
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.companyName
     *
     * @param companyname the value for company.companyName
     *
     * @mbg.generated Thu Mar 07 19:47:20 CST 2019
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.logo
     *
     * @return the value of company.logo
     *
     * @mbg.generated Thu Mar 07 19:47:20 CST 2019
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.logo
     *
     * @param logo the value for company.logo
     *
     * @mbg.generated Thu Mar 07 19:47:20 CST 2019
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.position
     *
     * @return the value of company.position
     *
     * @mbg.generated Thu Mar 07 19:47:20 CST 2019
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.position
     *
     * @param position the value for company.position
     *
     * @mbg.generated Thu Mar 07 19:47:20 CST 2019
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }
}