package com.restaurant.entity;

public class likeMenuKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likemenu.Id
     *
     * @mbg.generated Mon Mar 04 13:58:28 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likemenu.UserID
     *
     * @mbg.generated Mon Mar 04 13:58:28 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likemenu.MenuId
     *
     * @mbg.generated Mon Mar 04 13:58:28 CST 2019
     */
    private Integer menuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likemenu.Id
     *
     * @return the value of likemenu.Id
     *
     * @mbg.generated Mon Mar 04 13:58:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likemenu.Id
     *
     * @param id the value for likemenu.Id
     *
     * @mbg.generated Mon Mar 04 13:58:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likemenu.UserID
     *
     * @return the value of likemenu.UserID
     *
     * @mbg.generated Mon Mar 04 13:58:28 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likemenu.UserID
     *
     * @param userid the value for likemenu.UserID
     *
     * @mbg.generated Mon Mar 04 13:58:28 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likemenu.MenuId
     *
     * @return the value of likemenu.MenuId
     *
     * @mbg.generated Mon Mar 04 13:58:28 CST 2019
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likemenu.MenuId
     *
     * @param menuid the value for likemenu.MenuId
     *
     * @mbg.generated Mon Mar 04 13:58:28 CST 2019
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }
}