package com.restaurant.entity;

public class LikeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.UseId
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    private Integer useid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.PostId
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    private Integer postid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.CommentId
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    private Integer commentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.UseId
     *
     * @return the value of like.UseId
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public Integer getUseid() {
        return useid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.UseId
     *
     * @param useid the value for like.UseId
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public void setUseid(Integer useid) {
        this.useid = useid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.PostId
     *
     * @return the value of like.PostId
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public Integer getPostid() {
        return postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.PostId
     *
     * @param postid the value for like.PostId
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public void setPostid(Integer postid) {
        this.postid = postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.CommentId
     *
     * @return the value of like.CommentId
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public Integer getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.CommentId
     *
     * @param commentid the value for like.CommentId
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public void setCommentid(Integer commentid) {
        this.commentid = commentid;
    }
}