package com.restaurant.entity;

public class Menu extends MenuKey {

    private Restaurant restaurant;

    public Restaurant getRestaurant() {
        return restaurant;
    }

    public void setRestaurant(Restaurant restaurant) {
        this.restaurant = restaurant;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.Name
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.Materials
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    private String materials;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.Spicy
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    private Integer spicy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.CookWay
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    private String cookway;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.Picture
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.Price
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.SalePrice
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    private Double saleprice;

    private Integer score;

    private Boolean isLiked;

    private Integer postNum;

    public Integer getPostNum() {
        return postNum;
    }

    public void setPostNum(Integer postNum) {
        this.postNum = postNum;
    }

    public Boolean getLiked() {
        return isLiked;
    }

    public void setLiked(Boolean liked) {
        isLiked = liked;
    }

    public Integer getScore() {
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.Name
     *
     * @return the value of menu.Name
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.Name
     *
     * @param name the value for menu.Name
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.Materials
     *
     * @return the value of menu.Materials
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public String getMaterials() {
        return materials;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.Materials
     *
     * @param materials the value for menu.Materials
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public void setMaterials(String materials) {
        this.materials = materials == null ? null : materials.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.Spicy
     *
     * @return the value of menu.Spicy
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public Integer getSpicy() {
        return spicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.Spicy
     *
     * @param spicy the value for menu.Spicy
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public void setSpicy(Integer spicy) {
        this.spicy = spicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.CookWay
     *
     * @return the value of menu.CookWay
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public String getCookway() {
        return cookway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.CookWay
     *
     * @param cookway the value for menu.CookWay
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public void setCookway(String cookway) {
        this.cookway = cookway == null ? null : cookway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.Picture
     *
     * @return the value of menu.Picture
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.Picture
     *
     * @param picture the value for menu.Picture
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.Price
     *
     * @return the value of menu.Price
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.Price
     *
     * @param price the value for menu.Price
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.SalePrice
     *
     * @return the value of menu.SalePrice
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public Double getSaleprice() {
        return saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.SalePrice
     *
     * @param saleprice the value for menu.SalePrice
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public void setSaleprice(Double saleprice) {
        this.saleprice = saleprice;
    }
}