package com.restaurant.entity;

import java.util.Date;

public class Notice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.Id
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.Title
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.Content
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.RestaurantId
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    private Integer restaurantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.time
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.Id
     *
     * @return the value of notice.Id
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.Id
     *
     * @param id the value for notice.Id
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.Title
     *
     * @return the value of notice.Title
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.Title
     *
     * @param title the value for notice.Title
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.Content
     *
     * @return the value of notice.Content
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.Content
     *
     * @param content the value for notice.Content
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.RestaurantId
     *
     * @return the value of notice.RestaurantId
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public Integer getRestaurantid() {
        return restaurantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.RestaurantId
     *
     * @param restaurantid the value for notice.RestaurantId
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public void setRestaurantid(Integer restaurantid) {
        this.restaurantid = restaurantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.time
     *
     * @return the value of notice.time
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.time
     *
     * @param time the value for notice.time
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }
}