package com.restaurant.entity;

import java.util.Date;

public class Post extends PostKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.UserName
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.Title
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.Content
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.Type
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.Time
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.RestaurantId
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    private Integer restaurantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.Score
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.menuId
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    private Integer menuid;

    private Restaurant restaurant;

    public Restaurant getRestaurant() {
        return restaurant;
    }

    public void setRestaurant(Restaurant restaurant) {
        this.restaurant = restaurant;
    }

    private Menu menu;

    public Menu getMenu() {
        return menu;
    }

    public void setMenu(Menu menu) {
        this.menu = menu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.UserName
     *
     * @return the value of post.UserName
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.UserName
     *
     * @param username the value for post.UserName
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.Title
     *
     * @return the value of post.Title
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.Title
     *
     * @param title the value for post.Title
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.Content
     *
     * @return the value of post.Content
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.Content
     *
     * @param content the value for post.Content
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.Type
     *
     * @return the value of post.Type
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.Type
     *
     * @param type the value for post.Type
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.Time
     *
     * @return the value of post.Time
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.Time
     *
     * @param time the value for post.Time
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.RestaurantId
     *
     * @return the value of post.RestaurantId
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    public Integer getRestaurantid() {
        return restaurantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.RestaurantId
     *
     * @param restaurantid the value for post.RestaurantId
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    public void setRestaurantid(Integer restaurantid) {
        this.restaurantid = restaurantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.Score
     *
     * @return the value of post.Score
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.Score
     *
     * @param score the value for post.Score
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.menuId
     *
     * @return the value of post.menuId
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.menuId
     *
     * @param menuid the value for post.menuId
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    @Override
    public String toString() {
        return "Post{" +
                "username='" + username + '\'' +
                ", title='" + title + '\'' +
                ", content='" + content + '\'' +
                ", type='" + type + '\'' +
                ", time=" + time +
                ", restaurantid=" + restaurantid +
                ", score=" + score +
                ", menuid=" + menuid +
                ", restaurant=" + restaurant +
                '}';
    }
}