package com.restaurant.entity;

public class PostKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.id
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.UserId
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.id
     *
     * @return the value of post.id
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.id
     *
     * @param id the value for post.id
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.UserId
     *
     * @return the value of post.UserId
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.UserId
     *
     * @param userid the value for post.UserId
     *
     * @mbg.generated Fri Apr 19 14:16:09 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    @Override
    public String toString() {
        return "PostKey{" +
                "id=" + id +
                ", userid=" + userid +
                '}';
    }
}