package com.restaurant.entity;

import java.util.List;

public class Restaurant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.Id
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.Name
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.Position
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.WindowNum
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    private Integer windownum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.Company
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.Owner
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.Credit
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    private Integer credit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.ShortSaying
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    private String shortsaying;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.Score
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.password
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.Logo
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    private String logo;

    private List<Menu> menuList;

    private Notice notice;

    public Notice getNotice() {
        return notice;
    }

    public void setNotice(Notice notice) {
        this.notice = notice;
    }

    public List<Menu> getMenuList() {
        return menuList;
    }

    public void setMenuList(List<Menu> menuList) {
        this.menuList = menuList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.Id
     *
     * @return the value of restaurant.Id
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.Id
     *
     * @param id the value for restaurant.Id
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.Name
     *
     * @return the value of restaurant.Name
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.Name
     *
     * @param name the value for restaurant.Name
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.Position
     *
     * @return the value of restaurant.Position
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.Position
     *
     * @param position the value for restaurant.Position
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.WindowNum
     *
     * @return the value of restaurant.WindowNum
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    public Integer getWindownum() {
        return windownum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.WindowNum
     *
     * @param windownum the value for restaurant.WindowNum
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    public void setWindownum(Integer windownum) {
        this.windownum = windownum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.Company
     *
     * @return the value of restaurant.Company
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.Company
     *
     * @param company the value for restaurant.Company
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.Owner
     *
     * @return the value of restaurant.Owner
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.Owner
     *
     * @param owner the value for restaurant.Owner
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.Credit
     *
     * @return the value of restaurant.Credit
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.Credit
     *
     * @param credit the value for restaurant.Credit
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.ShortSaying
     *
     * @return the value of restaurant.ShortSaying
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    public String getShortsaying() {
        return shortsaying;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.ShortSaying
     *
     * @param shortsaying the value for restaurant.ShortSaying
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    public void setShortsaying(String shortsaying) {
        this.shortsaying = shortsaying == null ? null : shortsaying.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.Score
     *
     * @return the value of restaurant.Score
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.Score
     *
     * @param score the value for restaurant.Score
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.password
     *
     * @return the value of restaurant.password
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.password
     *
     * @param password the value for restaurant.password
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.Logo
     *
     * @return the value of restaurant.Logo
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.Logo
     *
     * @param logo the value for restaurant.Logo
     *
     * @mbg.generated Sun Apr 21 20:18:18 CST 2019
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }
}