package com.restaurant.entity;

import java.util.Date;

public class RestaurantReply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurantreply.id
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurantreply.commentId
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    private Integer commentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurantreply.restaurantId
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    private Integer restaurantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurantreply.content
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurantreply.time
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurantreply.id
     *
     * @return the value of restaurantreply.id
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurantreply.id
     *
     * @param id the value for restaurantreply.id
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurantreply.commentId
     *
     * @return the value of restaurantreply.commentId
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    public Integer getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurantreply.commentId
     *
     * @param commentid the value for restaurantreply.commentId
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    public void setCommentid(Integer commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurantreply.restaurantId
     *
     * @return the value of restaurantreply.restaurantId
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    public Integer getRestaurantid() {
        return restaurantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurantreply.restaurantId
     *
     * @param restaurantid the value for restaurantreply.restaurantId
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    public void setRestaurantid(Integer restaurantid) {
        this.restaurantid = restaurantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurantreply.content
     *
     * @return the value of restaurantreply.content
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurantreply.content
     *
     * @param content the value for restaurantreply.content
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurantreply.time
     *
     * @return the value of restaurantreply.time
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurantreply.time
     *
     * @param time the value for restaurantreply.time
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }
}