package com.restaurant.entity;

public class RestaurantKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.Id
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    private Integer id;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.Id
     *
     * @return the value of restaurant.Id
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.Id
     *
     * @param id the value for restaurant.Id
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

}