package com.restaurant.entity;

public class UserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Uid
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.XHid
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    private Integer xhid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Uid
     *
     * @return the value of user.Uid
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Uid
     *
     * @param uid the value for user.Uid
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.XHid
     *
     * @return the value of user.XHid
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public Integer getXhid() {
        return xhid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.XHid
     *
     * @param xhid the value for user.XHid
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public void setXhid(Integer xhid) {
        this.xhid = xhid;
    }
}