package com.restaurant.entity;

public class User extends UserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Name
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Gender
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ShortSaying
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    private String shortsaying;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Password
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Name
     *
     * @return the value of user.Name
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Name
     *
     * @param name the value for user.Name
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Gender
     *
     * @return the value of user.Gender
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Gender
     *
     * @param gender the value for user.Gender
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ShortSaying
     *
     * @return the value of user.ShortSaying
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public String getShortsaying() {
        return shortsaying;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ShortSaying
     *
     * @param shortsaying the value for user.ShortSaying
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public void setShortsaying(String shortsaying) {
        this.shortsaying = shortsaying == null ? null : shortsaying.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Password
     *
     * @return the value of user.Password
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Password
     *
     * @param password the value for user.Password
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}