package com.restaurant.mapper;

import com.restaurant.entity.LikeExample;
import com.restaurant.entity.LikeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    long countByExample(LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    int deleteByExample(LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    int deleteByPrimaryKey(LikeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    int insert(LikeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    int insertSelective(LikeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    List<LikeKey> selectByExample(LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") LikeKey record, @Param("example") LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbg.generated Thu Feb 28 13:11:42 CST 2019
     */
    int updateByExample(@Param("record") LikeKey record, @Param("example") LikeExample example);
}