package com.restaurant.mapper;

import com.restaurant.entity.likeMenu;
import com.restaurant.entity.likeMenuExample;
import com.restaurant.entity.likeMenuKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LikeMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likemenu
     *
     * @mbg.generated Mon Mar 04 13:58:28 CST 2019
     */
    long countByExample(likeMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likemenu
     *
     * @mbg.generated Mon Mar 04 13:58:28 CST 2019
     */
    int deleteByExample(likeMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likemenu
     *
     * @mbg.generated Mon Mar 04 13:58:28 CST 2019
     */
    int deleteByPrimaryKey(likeMenuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likemenu
     *
     * @mbg.generated Mon Mar 04 13:58:28 CST 2019
     */
    int insert(likeMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likemenu
     *
     * @mbg.generated Mon Mar 04 13:58:28 CST 2019
     */
    int insertSelective(likeMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likemenu
     *
     * @mbg.generated Mon Mar 04 13:58:28 CST 2019
     */
    List<likeMenu> selectByExample(likeMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likemenu
     *
     * @mbg.generated Mon Mar 04 13:58:28 CST 2019
     */
    likeMenu selectByPrimaryKey(likeMenuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likemenu
     *
     * @mbg.generated Mon Mar 04 13:58:28 CST 2019
     */
    int updateByExampleSelective(@Param("record") likeMenu record, @Param("example") likeMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likemenu
     *
     * @mbg.generated Mon Mar 04 13:58:28 CST 2019
     */
    int updateByExample(@Param("record") likeMenu record, @Param("example") likeMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likemenu
     *
     * @mbg.generated Mon Mar 04 13:58:28 CST 2019
     */
    int updateByPrimaryKeySelective(likeMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likemenu
     *
     * @mbg.generated Mon Mar 04 13:58:28 CST 2019
     */
    int updateByPrimaryKey(likeMenu record);
}