package com.restaurant.mapper;

import com.restaurant.entity.RestaurantReply;
import com.restaurant.entity.RestaurantReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RestaurantReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurantreply
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    long countByExample(RestaurantReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurantreply
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    int deleteByExample(RestaurantReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurantreply
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurantreply
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    int insert(RestaurantReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurantreply
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    int insertSelective(RestaurantReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurantreply
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    List<RestaurantReply> selectByExample(RestaurantReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurantreply
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    RestaurantReply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurantreply
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") RestaurantReply record, @Param("example") RestaurantReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurantreply
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    int updateByExample(@Param("record") RestaurantReply record, @Param("example") RestaurantReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurantreply
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    int updateByPrimaryKeySelective(RestaurantReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurantreply
     *
     * @mbg.generated Tue Apr 23 15:13:17 CST 2019
     */
    int updateByPrimaryKey(RestaurantReply record);
}